name: Docker Image CI

on:
  pull_request:
    types: [closed]

jobs:
     
  if_merged: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: | 
        echo "${{ secrets.DOCKERPW }}" | docker login -u tefegiando -p tefegiando
        docker image build -t apiv2 .
        docker tag apiv2 tefegiando/apiv2
        docker push tefegiando/apiv2
 
